import asyncio
import io
import sys
import uuid
from pathlib import Path

# Ensure backend root is in sys.path
backend_dir = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(backend_dir))

import pymupdf as fitz
import httpx
from sqlalchemy import select

from app.core.config import settings
from app.core.database import AsyncSessionLocal
from app.main import app
from app.models.document import Document, DocumentChunk
from app.services.storage import get_storage_service
from app.workers.tasks import _async_process_pdf, process_pdf_task


def create_synthetic_pdf(pages: int = 3) -> bytes:
    """Generates an in-memory PDF with known page counts and text."""
    doc = fitz.open()
    for page_idx in range(1, pages + 1):
        page = doc.new_page(width=595, height=842)
        text = (
            f"=== Scanity Test Document Page {page_idx} ===\n\n"
            f"This is section {page_idx}.1 of the test report for asynchronous Celery worker ingestion.\n"
            "PostgreSQL 16 with pgvector stores 768-dimensional embeddings generated by Gemini.\n"
            "Each chunk is carefully indexed with page numbers and sequence order for exact citations.\n\n"
            f"Key metrics for phase {page_idx}: latency is under 15ms, accuracy exceeds 99%.\n"
        )
        page.insert_text((50, 72), text, fontsize=12)

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


async def test_full_document_lifecycle():
    """
    Tests the complete end-to-end document lifecycle:
    1. Upload PDF via FastAPI endpoint (HTTP 202 Accepted, pending status)
    2. Execute background Celery ingestion task (pending -> processing -> ready)
    3. Verify pgvector chunk persistence and 768-dim embeddings
    4. Poll document status via GET /{id}/status (ready status)
    5. List documents via GET /
    6. Delete document via DELETE /{id} and verify database cascade and storage cleanup
    7. Verify edge cases (invalid format, empty file, 404s)
    """
    print("================================================================")
    print("Testing Step 5: Celery Worker & Document Endpoints Lifecycle")
    print("================================================================")

    pdf_bytes = create_synthetic_pdf(pages=3)
    transport = httpx.ASGITransport(app=app)

    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        # -------------------------------------------------------------
        # Test 1: Upload PDF document
        # -------------------------------------------------------------
        files = {"file": ("q3_financial_report.pdf", io.BytesIO(pdf_bytes), "application/pdf")}
        response = await client.post("/api/v1/documents/upload", files=files)
        
        assert response.status_code == 202, f"Upload failed: {response.text}"
        data = response.json()
        doc_id = uuid.UUID(data["document_id"])
        assert data["original_filename"] == "q3_financial_report.pdf"
        assert data["status"] == "pending"
        print(f"PASS [1/7]: Uploaded document {doc_id} with status 'pending' (HTTP 202).")

        # Verify DB has pending record
        async with AsyncSessionLocal() as session:
            db_doc = await session.get(Document, doc_id)
            assert db_doc is not None, "Document not found in database!"
            assert db_doc.status == "pending"
            storage_path = db_doc.storage_path
            assert Path(storage_path).exists(), f"Stored file {storage_path} does not exist on disk!"

        # -------------------------------------------------------------
        # Test 2: Execute Ingestion Task
        # -------------------------------------------------------------
        print("Executing ingestion worker processing...")
        task_result = await _async_process_pdf(str(doc_id), storage_path)
        assert task_result["status"] == "ready"
        assert task_result["page_count"] == 3
        assert task_result["total_chunks"] >= 3
        print(f"PASS [2/7]: Worker processed {task_result['page_count']} pages into {task_result['total_chunks']} chunks.")

        # -------------------------------------------------------------
        # Test 3: Verify PostgreSQL pgvector Chunks & Embeddings
        # -------------------------------------------------------------
        async with AsyncSessionLocal() as session:
            chunks_result = await session.execute(
                select(DocumentChunk).where(DocumentChunk.document_id == doc_id).order_by(DocumentChunk.chunk_index)
            )
            chunks = chunks_result.scalars().all()
            assert len(chunks) == task_result["total_chunks"], "Chunk count mismatch in DB!"
            
            for chunk in chunks:
                assert chunk.page_number in (1, 2, 3)
                assert chunk.embedding is not None
                assert len(chunk.embedding) == settings.VECTOR_DIMENSION
            print(f"PASS [3/7]: Verified {len(chunks)} chunks in PostgreSQL with {settings.VECTOR_DIMENSION}-dim embeddings.")

        # -------------------------------------------------------------
        # Test 4: Poll Document Status via GET /{id}/status
        # -------------------------------------------------------------
        status_resp = await client.get(f"/api/v1/documents/{doc_id}/status")
        assert status_resp.status_code == 200, f"Status fetch failed: {status_resp.text}"
        status_data = status_resp.json()
        assert status_data["id"] == str(doc_id)
        assert status_data["status"] == "ready"
        assert status_data["page_count"] == 3
        assert status_data["total_chunks"] == len(chunks)
        print(f"PASS [4/7]: GET /{doc_id}/status returned 'ready' with {status_data['total_chunks']} chunks.")

        # -------------------------------------------------------------
        # Test 5: List Documents via GET /
        # -------------------------------------------------------------
        list_resp = await client.get("/api/v1/documents")
        assert list_resp.status_code == 200
        list_data = list_resp.json()
        assert list_data["total"] >= 1
        doc_ids = [d["id"] for d in list_data["documents"]]
        assert str(doc_id) in doc_ids
        print(f"PASS [5/7]: GET /api/v1/documents successfully listed {list_data['total']} documents.")

        # -------------------------------------------------------------
        # Test 6: Delete Document & Cascade Verification
        # -------------------------------------------------------------
        del_resp = await client.delete(f"/api/v1/documents/{doc_id}")
        assert del_resp.status_code == 200
        print(f"Deleted document {doc_id}.")

        # Verify DB document is gone
        async with AsyncSessionLocal() as session:
            doc_check = await session.get(Document, doc_id)
            assert doc_check is None, "Document still exists in DB after deletion!"

            # Verify chunks were cascaded and deleted automatically
            chunks_check = await session.execute(
                select(DocumentChunk).where(DocumentChunk.document_id == doc_id)
            )
            assert len(chunks_check.scalars().all()) == 0, "Document chunks were not cascaded upon deletion!"

        # Verify physical file was deleted from disk
        assert not Path(storage_path).exists(), f"Physical file {storage_path} was not deleted from disk!"
        print("PASS [6/7]: DELETE /{id} deleted DB record, cascaded all pgvector chunks, and deleted disk file.")

        # -------------------------------------------------------------
        # Test 7: Edge Cases & Validation
        # -------------------------------------------------------------
        # Invalid file type
        bad_file = {"file": ("test.txt", io.BytesIO(b"Hello text file"), "text/plain")}
        bad_resp = await client.post("/api/v1/documents/upload", files=bad_file)
        assert bad_resp.status_code == 400

        # Empty file
        empty_file = {"file": ("empty.pdf", io.BytesIO(b""), "application/pdf")}
        empty_resp = await client.post("/api/v1/documents/upload", files=empty_file)
        assert empty_resp.status_code == 400

        # Non-existent document 404
        fake_uuid = uuid.uuid4()
        not_found_resp = await client.get(f"/api/v1/documents/{fake_uuid}/status")
        assert not_found_resp.status_code == 404

        print("PASS [7/7]: Edge cases handled correctly (invalid extensions, empty uploads, 404 lookups).")

    print("\nALL DOCUMENT LIFECYCLE TESTS PASSED SUCCESSFULLY!\n")


if __name__ == "__main__":
    asyncio.run(test_full_document_lifecycle())
